module.exports = {
  POST_IMAGE: 'POST_IMAGE',
  IMAGE_POSTED: 'IMAGE_POSTED',

  LOAD_RESULTS: 'LOAD_RESULTS',
  RESULTS_LOADED: 'RESULTS_LOADED',

  LOADING_TRANSLATIONS: 'LOADING_TRANSLATIONS',
  TRANSLATIONS_LOADED: 'TRANSLATIONS_LOADED',
};